BakeryWeb/Models/UOM.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOM
    {
        public int UOMCode { get; set; }
        public string UOMShortName { get; set; }
        public string UOMLongName { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
    }
}

BakeryWeb/Controllers/UOMController.cs
using BakeryWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace BakeryWeb.Controllers
{
    public class UOMController : Controller
    {
        // GET: UOM

        string Exception;
        string ExceptionMessage;
        string UserName;
        string Action;
        string ApplicationMessage;
        string SortOption = String.Empty;
        string SortColumn = String.Empty;
        string SortIcon = String.Empty;
        Dictionary<string, string> DataObjDict = new Dictionary<string, string>();
        Dictionary<int, string> UOMDict = new Dictionary<int, string>();
        List<UOM> UOMList = new List<UOM>();
        List<DisplayView> DisplayViewList = new List<DisplayView>();

        public class DisplayView
        {
            public string UOMCode { get; set; }
            public string UOMShortName { get; set; }
            public string UOMLongName { get; set; }
            public string Active { get; set; }
            public string Deleted { get; set; }
            public string CreateUser { get; set; }
            public string CreateDate { get; set; }
        }



        public class ResponseData
        {
            public string Action { get; set; }
            public string Exception { get; set; }
            public string ExceptionMessage { get; set; }
            public string ApplicationMessage { get; set; }
            public List<DisplayView> DisplayViewList { get; set; }
            public string RecordCount { get; set; }
            public string DisplayTime { get; set; }
            public string SortColumn { get; set; }
            public string SortIcon { get; set; }




        }
        public ActionResult Index()
        {
            ViewBag.Title = "Bakery Web";
            ViewBag.SubTitle = "Units Of Measurement";
            ViewBag.LastUpdate = "[Last Update Friday 05/02/2025 6:07 PM CST]";
            ViewBag.UserName = "pmanuel";
            return View();
        }

        public ActionResult AJAXGetData(string dataObj)
        {
            AJAXInit(dataObj);
            using (var db = new pmanuelEntities())
            {
                LoadDictionaries(db);
                LoadData(db);
                FormatData();
                SortData();
            }
            ExecuteProcedures();
            return Json(new ResponseData
            {
                Action = Action,
                DisplayTime = DateTime.Now.ToString(),
                DisplayViewList = DisplayViewList,
                RecordCount = DisplayViewList.Count.ToString(),
                SortColumn = SortColumn,
                SortIcon = SortIcon,
                Exception = Exception,
                ExceptionMessage = ExceptionMessage,
                ApplicationMessage = ApplicationMessage
            }, JsonRequestBehavior.DenyGet);
        }
        public void AJAXInit(string AJAXDataObject)
        {
            GetAuthorizations();
            if (String.IsNullOrWhiteSpace(AJAXDataObject))
                return;
            var jss = new JavaScriptSerializer();
            DataObjDict = jss.Deserialize<Dictionary<string, string>>(AJAXDataObject);
            Exception = "N";
            ExceptionMessage = String.Empty;
            ExtractData();
        }


        private void GetAuthorizations()
        {
            UserName = String.IsNullOrEmpty(User.Identity.Name) ? "No Name" : User.Identity.Name.Replace("RRSP\\", "").ToUpper();
            ViewBag.UserName = UserName;
            return;
        }

        private void ExtractData()
        {
            foreach (var item in DataObjDict)
            {
                if (String.IsNullOrWhiteSpace(item.Value))
                    continue;
                string value = item.Value.Trim().ToUpper();
                switch (item.Key)
                {
                    case "Action":
                        Action = value;
                        break;
                    case "SortOption":
                        SortOption = value;
                        break;
                }
            }
        }


        private void ExecuteProcedures()
        {
            using (var db = new pmanuelEntities())
            {
                switch (Action)
                {
                    case "RESETDATA":
                        var rdResult = db.bdbResetData();
                        ApplicationMessage = "Data Reset";
                        break;
                    case "RESETSCHEMA":
                        var rsResult2 = db.bdbResetSchema();
                        ApplicationMessage = "Schema Reset. Must Reset Data.";
                        break;
                }
            }
        }

        private void LoadData(pmanuelEntities db)
        {
            UOMList = (from s in db.UOMs
                             where s.Active == true
                             && s.Deleted == false
                             select s).ToList();
            if (!UOMList.Any())
            {
                Exception = "Y";
                ExceptionMessage = "There were no UOM records.";
                return;
            }
        }

        private void FormatData()
        {
            foreach (var item in UOMList)
            {
                var entry = new DisplayView()
                {
                    UOMCode = item.UOMCode.ToString(),
                    UOMShortName = item.UOMShortName.ToString(),
                    UOMLongName = item.UOMLongName,
                    Active = item.Active ? "Y" : "N",
                    Deleted = item.Deleted ? "Y" : "N",
                    CreateUser = item.CreateUser,
                    CreateDate = item.CreateDate.ToString()
                };
                DisplayViewList.Add(entry);
                entry.UOMShortName = UOMDict.TryGetValue(item.UOMCode, out string UOMShortName) ? UOMShortName : "N/A";

            }
        }

        private void SortData()
        {
            SortIcon = String.Empty;
            switch (SortOption)
            {
                case "1":
                    DisplayViewList = DisplayViewList.OrderBy(a => Convert.ToInt32(a.UOMCode)).ToList();
                    SortIcon = "bi-caret-up-fill";
                    SortColumn = "UOMCode";
                    break;
                case "2":
                    DisplayViewList = DisplayViewList.OrderByDescending(a => Convert.ToInt32(a.UOMCode)).ToList();
                    SortIcon = "bi-caret-down-fill";
                    SortColumn = "UOMCode";
                    break;
                case "3":
                    DisplayViewList = DisplayViewList.OrderBy(a => a.UOMShortName).ToList();
                    SortIcon = "bi-caret-up-fill";
                    SortColumn = "UOMShortName";
                    break;
                case "4":
                    DisplayViewList = DisplayViewList.OrderByDescending(a => a.UOMShortName).ToList();
                    SortIcon = "bi-caret-down-fill";
                    SortColumn = "UOMShortName";
                    break;
                case "5":
                    DisplayViewList = DisplayViewList.OrderBy(a => a.UOMLongName).ToList();
                    SortIcon = "bi-caret-up-fill";
                    SortColumn = "UOMLongName";
                    break;
                case "6":
                    DisplayViewList = DisplayViewList.OrderByDescending(a => a.UOMLongName).ToList();
                    SortIcon = "bi-caret-down-fill";
                    SortColumn = "UOMLongName";
                    break;
                case "7":
                    DisplayViewList = DisplayViewList.OrderBy(a => a.Active).ToList();
                    SortIcon = "bi-caret-up-fill";
                    SortColumn = "Active";
                    break;
                case "8":
                    DisplayViewList = DisplayViewList.OrderByDescending(a => a.Active).ToList();
                    SortIcon = "bi-caret-down-fill";
                    SortColumn = "Active";
                    break;
                case "9":
                    DisplayViewList = DisplayViewList.OrderBy(a => a.Deleted).ToList();
                    SortIcon = "bi-caret-up-fill";
                    SortColumn = "Deleted";
                    break;
                case "10":
                    DisplayViewList = DisplayViewList.OrderByDescending(a => a.Deleted).ToList();
                    SortIcon = "bi-caret-down-fill";
                    SortColumn = "Deleted";
                    break;
                case "11":
                    DisplayViewList = DisplayViewList.OrderBy(a => a.CreateUser).ToList();
                    SortIcon = "bi-caret-up-fill";
                    SortColumn = "CreateUser";
                    break;
                case "12":
                    DisplayViewList = DisplayViewList.OrderByDescending(a => a.CreateUser).ToList();
                    SortIcon = "bi-caret-down-fill";
                    SortColumn = "CreateUser";
                    break;
                case "13":
                    DisplayViewList = DisplayViewList.OrderBy(a => Convert.ToDateTime(a.CreateDate)).ToList();
                    SortIcon = "bi-caret-up-fill";
                    SortColumn = "CreateDate";
                    break;
                case "14":
                    DisplayViewList = DisplayViewList.OrderByDescending(a => Convert.ToDateTime(a.CreateDate)).ToList();
                    SortIcon = "bi-caret-down-fill";
                    SortColumn = "CreateDate";
                    break;
                default:

BakeryWeb/Views/UOM/Index.cshtml

@{
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}


@*<h2>UOM</h2>*@

<script>


    var config = {
        GetData: {
            url: '@Url.Action("AJAXGetData", "UOM")'
        }
    };


    function GetData(action, sortOption) {
        //alert(action)
        let dataObj = JSON.stringify({
            Action: action,
            SortOption: sortOption,
        });
        $.ajax({
            type: "POST",
            url: config.GetData.url,
            data: JSON.stringify(dataObj),
            data: { "dataObj": dataObj },
            cache: false,
            success: function (response) {
                if (response.Exception == "N") {
                    $("#recordsReturned").html(`<h4 class='alert alert-primary' style='text-align: center; font-size: medium; font-weight: bold; width: 90%; border: 1px solid black; border-color: #000000; background-color: #cc7b9d; color: #ffffff;'>` +
                        `${response.RecordCount} Items - Current as of: ${response.DisplayTime}</h4>`);
                    if (response.RecordCount > 0) {
                        showData(response);
                        $("#content").show();
                    }
                    else {
                        $("#divMsg").html(`<label class='alert alert-danger' style='text-align: center; font-size: medium; font-weight: bold'>${response.ApplicationMessage}</label>`);
                        $("#content").hide();
                    }
                }
                else {
                    $("#divMsg").html(`<label class='alert alert-danger' style='text-align: center; font-size: medium; font-weight: bold'>${response.ExceptionMessage}</label>`);
                    $("#content").hide();
                }
            },
        });
    }
    $(document).ready(function () {
        GetData("GET", "1");
    });

    function showData(response) {
        let spanNoIcon = '</th>';
        let spanIcon = `<span class="${response.SortIcon}"></span></th>`;
        let font = "font-size: 16px; color: #ffffff;";
        let rowColor = "#c41c46";
        let html = "";
        html += `<tr style="background-color: ${rowColor}; border-color: #000000;">`;
        //html += `<th style="display: none;" field="LocationID"></th>`;   // display LocationID
        html += `<th style="text-align: center; width: 10px; font-size: 12px; color: #ffffff" field="UOMCode" onclick="sortByField(this); return false;"><a>UOM ID</a>`;
        html += response.SortColumn == "UOMCode" ? spanIcon : spanNoIcon;
        html += `<th style="text-align: center; width: 10px; font-size: 12px; color: #ffffff" field="UOMShortName" onclick="sortByField(this); return false;"><a>UOM Short Name</a>`;
        html += response.SortColumn == "UOMShortName" ? spanIcon : spanNoIcon;
        html += `<th style="text-align: center; width: 10px; font-size: 12px; color: #ffffff" field="UOMLongName" onclick="sortByField(this); return false;"><a>UOM Long Name</a>`;
        html += response.SortColumn == "UOMLongName" ? spanIcon : spanNoIcon;
        html += `<th style="text-align: center; width: 10px; font-size: 12px; color: #ffffff" field="Active" onclick="sortByField(this); return false;"><a>Active</a>`;
        html += response.SortColumn == "Active" ? spanIcon : spanNoIcon;
        html += `<th style="text-align: center; width: 10px; font-size: 12px; color: #ffffff" field="Deleted" onclick="sortByField(this); return false;"><a>Deleted</a>`;
        html += response.SortColumn == "Deleted" ? spanIcon : spanNoIcon;
        html += `<th style="text-align: center; width: 10px; font-size: 12px; color: #ffffff" field="CreateUser" onclick="sortByField(this); return false;"><a>Create User</a>`;
        html += response.SortColumn == "CreateUser" ? spanIcon : spanNoIcon;
        html += `<th style="text-align: center; width: 10px; font-size: 12px; color: #ffffff" field="CreateDate" onclick="sortByField(this); return false;"><a>Create Date</a>`;
        html += response.SortColumn == "CreateDate" ? spanIcon : spanNoIcon;
        html += `</tr>`;
        $("#tblData thead").html(html);
        html = ``;
        for (i = 0; i < response.RecordCount; ++i) {
            rowColor = rowColor == "#cc7b9d" ? "#c41c46" : "#cc7b9d";
            html += `<tr style="background-color: ${rowColor}; border-color: #000000;">`;
            html += `<td style="text-align: center; ${font}">${response.DisplayViewList[i].UOMCode}</td>`;
            html += `<td style="text-align: center; ${font}">${response.DisplayViewList[i].UOMShortName}</td>`;
            html += `<td style="text-align: center; ${font}">${response.DisplayViewList[i].UOMLongName}</td>`;
            html += `<td style="text-align: center; ${font}">${response.DisplayViewList[i].Active}</td>`;
            html += `<td style="text-align: center; ${font}">${response.DisplayViewList[i].Deleted}</td>`;
            html += `<td style="text-align: center; ${font}">${response.DisplayViewList[i].CreateUser}</td>`;
            html += `<td style="text-align: center; ${font}">${response.DisplayViewList[i].CreateDate}</td>`;
            html += `</tr>`;
        }
        $("#tblData tbody").html(html);
    }
    function sortByField(obj) {
        let columnName = $(obj).attr("field");
        let sortA = $(obj).find("span").hasClass("bi-caret-up-fill");
        let sortOption = "";;
        switch (columnName) {
            case "UOMCode":
                sortOption = sortA ? "2" : "1";
                break;
            case "UOMShortName":
                sortOption = sortA ? "4" : "3";
                break;
            case "UOMLongName":
                sortOption = sortA ? "6" : "5";
                break;
            case "Active":
                sortOption = sortA ? "8" : "7";
                break;
            case "Deleted":
                sortOption = sortA ? "10" : "9";
                break;
            case "CreateUser":
                sortOption = sortA ? "12" : "11";
                break;
            case "CreateDate":
                sortOption = sortA ? "14" : "13";
                break;
        }
        GetData("GET", sortOption)
    }

</script>

<div id="content">
    <button onclick="scrollToTop()" id="btnToTop" class="btn btn-primary" title="Go to top" style="width: 50px; position: fixed; bottom: 60px; right: 25px; z-index: 99; background-color: #cc7b9d; border-color: #000000;"><span class="bi-arrow-up"></span></button>
    <button onclick="scrollToBottom()" id="btnToBottom" class="btn btn-primary" title="Go to bottom" style="width: 50px; position: fixed; bottom: 20px; right: 25px; z-index: 99; background-color: #cc7b9d; border-color: #000000;"><span class="bi-arrow-down"></span></button>
    <div id="recordsReturned"></div>
    <table id="tblData" class="table" style="table-layout: fixed; border: 1px solid black; border-color: #000000; width: 90%;">
        <thead></thead>
        <tbody></tbody>
    </table>
</div>
<div id="divMsg"></div>